// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziiuykwfzruwgfwweiyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppaXV5a3dmenJ1d2dmd3dlaXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTMzMDEsImV4cCI6MjA3MTA4OTMwMX0.QkXHOOQK8R-VznjUXRKIdQP8HUqvKE7fC4IhcRSPlNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});